import React from 'react';
import {
  ActivityIndicator,
  Pressable,
  StyleProp,
  StyleSheet,
  Text,
  TextStyle,
  View,
  ViewStyle,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';

import { useAppTheme } from '@/hooks/useAppTheme';
import {
  Bloom,
  Gradients,
  Radius,
  Typography,
  type BloomSpec,
  type GradientName,
} from '@/constants/theme';
import { useColorScheme } from '@/hooks/use-color-scheme';

type Size = 'cta' | 'mini' | 'fab' | 'segment';

type Props = {
  label?: string;
  icon?: React.ComponentProps<typeof MaterialIcons>['name'];
  onPress?: () => void;
  /** `neutral` resolves to the dark ramp on light mode and vice versa. */
  variant?: GradientName | 'neutral';
  size?: Size;
  disabled?: boolean;
  loading?: boolean;
  style?: StyleProp<ViewStyle>;
  labelStyle?: StyleProp<TextStyle>;
  accessibilityLabel?: string;
  children?: React.ReactNode;
};

const SIZES: Record<Size, { height: number; font: number; icon: number; padH: number }> = {
  cta: { height: 52, font: 15, icon: 20, padH: 20 },
  mini: { height: 44, font: 14, icon: 17, padH: 18 },
  fab: { height: 56, font: 0, icon: 26, padH: 0 },
  segment: { height: 36, font: 12.5, icon: 15, padH: 10 },
};

const BLOOM: Record<Size, BloomSpec> = {
  cta: Bloom.cta,
  mini: Bloom.mini,
  fab: Bloom.fab,
  segment: Bloom.segment,
};

/**
 * The gradient ramp — expo-linear-gradient renders natively on both iOS and
 * Android with no ID-namespace issues and guaranteed full-width fill. It
 * replaced the earlier react-native-svg approach which suffered gradient-ID
 * collisions when multiple GradientButton instances shared the short IDs
 * generated by React.useId(), causing the gradient to visually "restart" at
 * ~90% of the button width.
 */
function Ramp({
  colors,
  locations = [0, 0.52, 1],
}: {
  colors: readonly string[];
  locations?: number[];
}) {
  return (
    <LinearGradient
      colors={colors as [string, string, ...string[]]}
      locations={locations as [number, number, ...number[]]}
      start={{ x: 0, y: 0.5 }}
      end={{ x: 1, y: 0.5 }}
      style={StyleSheet.absoluteFill}
    />
  );
}

/** The sheen over the top of a pill. Barely there, on purpose. */
function Sheen({ strong }: { strong?: boolean }) {
  return (
    <LinearGradient
      colors={['rgba(255,255,255,' + (strong ? '0.28' : '0.06') + ')', 'rgba(255,255,255,0)']}
      locations={[0, 0.55]}
      start={{ x: 0.5, y: 0 }}
      end={{ x: 0.5, y: 1 }}
      style={StyleSheet.absoluteFill}
    />
  );
}

/**
 * The primary material — a gradient pill.
 *
 * Four layers, per DESIGN.md § Components: a horizontal gradient ramp, a same-hue
 * bloom, a faint top sheen, and a compressing overlay while pressed. The radius
 * is always half the height, at every size, so a 44px secondary button and a
 * 52px CTA are the same shape at different scales.
 *
 * A disabled button drops the gradient AND the bloom entirely — a disabled
 * control must never glow, which is the clearest single signal in the system.
 */
export function GradientButton({
  label,
  icon,
  onPress,
  variant = 'primary',
  size = 'cta',
  disabled,
  loading,
  style,
  labelStyle,
  accessibilityLabel,
  children,
}: Props) {
  const theme = useAppTheme();
  const isDark = useColorScheme() === 'dark';
  const dims = SIZES[size];
  const bloom = BLOOM[size];

  const rampName: GradientName =
    variant === 'neutral' ? (isDark ? 'neutralLight' : 'neutralDark') : variant;
  const ramp = Gradients[rampName];
  const isLightRamp = rampName === 'neutralLight';

  const press = useSharedValue(0);
  const animStyle = useAnimatedStyle(() => ({
    transform: [
      { translateY: withTiming(press.value * 1.5, { duration: press.value ? 120 : 180 }) },
      { scale: withTiming(1 - press.value * 0.012, { duration: press.value ? 120 : 180 }) },
    ],
  }));
  const dimStyle = useAnimatedStyle(() => ({
    opacity: withTiming(press.value * 0.16, { duration: press.value ? 120 : 180 }),
  }));

  const radius = dims.height / 2;
  const isDisabled = disabled || loading;

  const body = children ?? (
    <View style={styles.row}>
      {icon ? (
        <MaterialIcons
          name={icon}
          size={dims.icon}
          color={isDisabled ? theme.textTertiary : ramp.on}
        />
      ) : null}
      {label ? (
        <Text
          numberOfLines={1}
          style={[
            styles.label,
            { fontSize: dims.font, color: isDisabled ? theme.textTertiary : ramp.on },
            labelStyle,
          ]}
        >
          {label}
        </Text>
      ) : null}
    </View>
  );

  // Disabled: flat track fill, no gradient, no bloom, no shadow.
  if (isDisabled) {
    return (
      <View
        accessibilityRole="button"
        accessibilityState={{ disabled: true }}
        accessibilityLabel={accessibilityLabel ?? label}
        style={[
          styles.base,
          {
            height: dims.height,
            borderRadius: radius,
            paddingHorizontal: dims.padH,
            backgroundColor: theme.segmentTrackBg,
            width: size === 'fab' ? dims.height : '100%',
          },
          style,
        ]}
      >
        {loading ? <ActivityIndicator color={theme.textTertiary} /> : body}
      </View>
    );
  }

  return (
    <Animated.View
      style={[
        {
          borderRadius: radius,
          // The bloom. iOS renders shadowColor directly; Android honours it from
          // API 28 and falls back to a neutral elevation shadow below that.
          shadowColor: ramp.mid,
          shadowOpacity: bloom.opacity,
          shadowRadius: bloom.radius,
          shadowOffset: { width: 0, height: bloom.offsetY },
          elevation: bloom.elevation,
          width: size === 'fab' ? dims.height : '100%',
        },
        animStyle,
        style,
      ]}
    >
      <Pressable
        accessibilityRole="button"
        accessibilityLabel={accessibilityLabel ?? label}
        onPress={onPress}
        onPressIn={() => {
          press.value = 1;
        }}
        onPressOut={() => {
          press.value = 0;
        }}
        style={[
          styles.base,
          {
            height: dims.height,
            borderRadius: radius,
            paddingHorizontal: dims.padH,
            width: size === 'fab' ? dims.height : '100%',
            backgroundColor: ramp.mid,
            overflow: 'hidden',
          },
        ]}
      >
        <Ramp colors={ramp.colors} />
        <Sheen strong={isLightRamp} />
        <Animated.View
          pointerEvents="none"
          style={[StyleSheet.absoluteFill, { backgroundColor: '#000' }, dimStyle]}
        />
        {body}
      </Pressable>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  base: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  label: {
    ...Typography.bodySemibold,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
});

/** Flat gradient fill with no press behaviour — for the segmented indicator. */
export function GradientFill({
  variant = 'primary',
  radius = Radius.md,
  style,
}: {
  variant?: GradientName;
  radius?: number;
  style?: StyleProp<ViewStyle>;
}) {
  const ramp = Gradients[variant];
  return (
    <View style={[{ borderRadius: radius, overflow: 'hidden' }, style]}>
      <Ramp colors={ramp.colors} />
    </View>
  );
}
